### ISSUE TITLE
dependent type in impl/hashtable.h

### ISSUE THREAD

**Issue by boxdot** [yandex/mms#6]
These two lines 58 and 59 in `include/mms/impl/hashtable.h` are not compiling under clang (clang-600.0.57)
```c++
const_local_iterator begin(size_t bucket) const { return buckets_[bucket].ptr<Value>(); }
const_local_iterator end  (size_t bucket) const { return buckets_[bucket+1].ptr<Value>(); }
```
with the error: use 'template' keyword to treat 'ptr' as a dependent template name.

Adding the `template` keyword resolves the problem.

**Comment by dprokoptsev** [comment]
Fixed in a3ffdb8.
